[tox]
envlist=linting,unittesting
minversion = 4.0
skipsdist = True
toxworkdir=/tmp/.tox

[testenv]
passenv = *

usedevelop = True
install_command = pip install -U {opts} {packages}
deps = -e {env:HOME}/fusion-common
       -e {env:HOME}/fusion-agent
       -e {env:HOME}/fusion-manager/mgmtworker
       -e {env:HOME}/cloudify-utilities-plugins-sdk
       -r{toxinidir}/requirements.txt
       -r{toxinidir}/test-requirements.txt
whitelist_externals = bash

[testenv:unittesting]
commands= 
       coverage erase
       coverage run --source=cloudify_tf -m nose2 -s cloudify_tf
       coverage report -m

[testenv:linting]
commands=flake8 cloudify_tf

[coverage:run]
omit = 
       cloudify_tf/tests/*
       cloudify_tf/tests/*/*
       cloudify_tf/terraform/tests/*
